repo_url: "https://github.com/openucx/ucc.git"
work_dir: "/tmp/hpc-perf-monitor"
ref_commit: "master"
test_commits:
  - "HEAD~1"
  - "HEAD"

build:
  source_dir: "/tmp/hpc-perf-monitor/source"
  build_dir: "/tmp/hpc-perf-monitor/build"
  configure_flags:
    - "--enable-debug"
    - "--with-cuda=/usr/local/cuda"
  make_flags:
    - ""
  env_vars:
    CC: "gcc"
    CXX: "g++"

benchmarks:
  # - name: "ucc_perftest_allgather"
  #   type: "ucc"
  #   benchmark_dir: "/tmp/hpc-perf-monitor/build/bin"
  #   command: "ucc_perftest -c allgather -F -m cuda -b 1 -e 32k"
  #   params:
  #     num_processes: [2]
  #     procs_per_node: [1]
  #     memory_types: ["cuda"]
  #   parser: "ucc_perftest"
  #   metrics: ["latency_avg", "bandwidth_avg"]
  # - name: "ucc_perftest_allgather"
  #   type: "ucc"
  #   benchmark_dir: "/tmp/hpc-perf-monitor/build/bin"
  #   command: "ucc_perftest -c allgather -F -m host -b 1 -e 32k"
  #   params:
  #     num_processes: [2]
  #     procs_per_node: [1]
  #     memory_types: ["host"]
  #   parser: "ucc_perftest"
  #   metrics: ["latency_avg", "bandwidth_avg"]
  - name: "osu_bcast"
    type: "osu"
    benchmark_dir: "/global/exafs/users/ikryukov/hpcx-v2.22.1-gcc-doca_ofed-redhat9-cuda12-aarch64/ompi/tests/osu-micro-benchmarks-cuda/"
    command: "osu_bcast -i 100000 --full"
    mpi_args: "-x CUDA_VISIBLE_DEVICES=0 --mca coll_hcoll_enable 0 --mca coll_ucc_enable 1 --mca coll_ucc_priority 100"
    params:
      num_processes: [8]
      procs_per_node: [1]
      memory_types: ["cuda"]
    parser: "osu_bench"
    metrics: ["latency_max"]
    slurm:
      partition: "gh"
      time_limit: "00:30:00"
      output_dir: "/global/exafs/users/ikryukov/results"
      job_name: "osu_bcast"

  # - name: "osu_bcast"
  #   type: "osu"
  #   benchmark_dir: "/home/ilya/work/hpcx/ompi/tests/osu-micro-benchmarks/"
  #   command: "osu_bcast -i 100000 --full"
  #   params:
  #     num_processes: [2]
  #     procs_per_node: [1]
  #     memory_types: ["host"]
  #   parser: "osu_bench"
  #   metrics: ["latency_max"]
  # - name: "osu_allgather"
  #   type: "osu"
  #   benchmark_dir: "/home/ilya/work/hpcx/ompi/tests/osu-micro-benchmarks/"
  #   command: "osu_allgather -i 20000 --full"
  #   params:
  #     num_processes: [2]
  #     procs_per_node: [1]
  #     memory_types: ["host"]
  #   parser: "osu_bench"
  #   metrics: ["latency_avg"]

regression:
  threshold_pct: 5.0
  min_runs: 1
  metrics_weight:
    latency_avg: 1.0
    bandwidth_avg: 1.0

report_formats:
  - "html"
  - "markdown"